# Generated by Django 3.0.3 on 2020-03-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lr_leave', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Daily_Details',
        ),
        migrations.DeleteModel(
            name='Add_employee',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Request_leave',
        ),
    ]
